service: 2022project
provider:
  name : aws
  runtime: python3.7
  profile: 2022project
  region: ap-northeast-2
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action: 
      - s3:getObject
      Resource: arn:aws:s3:::2022project/models/*
    - Effect: Allow
      Action:
        - "lambda:InvokeFuntion"
      Resource: "*"

custom:
  pythonRequirements:
    dockerizePip : true
    zip : true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"
  warmup:
    events:
      -schedule: "rate(5 mintues)"
    timeout : 50

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/pytorch_model.bin
    - raw/**
    - .vscode/**
    - .ipynb_checkpoints/**

/*inovke our lambda funcitons */

functions:
  transformImage:
    handler: src/handler.lambda_handler
    memorySize: 3088
    timeout: 300
    events:
      - http:
         path: transform
         method:  post
         cors: true
    warmup : true

// plugins section
plugins:
  - serverless -python-requirements
  - serverless -plugin-warmup